import { FloatingShapeProps } from "@/presentation/components/common/FloatingShapes/FloatingShapes";

export const floatingShapesConfig: FloatingShapeProps[] = [
  {
    size: "lg" as const,
    shape: "diamond" as const,
    position: { top: "1/8", left: "1/8" },
    animationDelay: 0,
    opacity: 0.05,
    borderWidth: 2 as const,
  },
  {
    size: "sm" as const,
    shape: "triangle" as const,
    position: { top: "1/4", left: "1/6" },
    animationDelay: 800,
    opacity: 0.08,
    borderWidth: 3 as const,
  },
  {
    size: "md" as const,
    shape: "circle" as const,
    position: { top: "1/6", left: "1/3" },
    animationDelay: 1200,
    opacity: 0.06,
    borderWidth: 2 as const,
  },
  {
    size: "xl" as const,
    shape: "circle" as const,
    position: { top: "1/12", right: "1/8" },
    animationDelay: 400,
    opacity: 0.04,
    borderWidth: 1 as const,
  },
  {
    size: "md" as const,
    shape: "diamond" as const,
    position: { top: "1/3", right: "1/6" },
    animationDelay: 1600,
    opacity: 0.07,
    borderWidth: 3 as const,
  },
  {
    size: "sm" as const,
    shape: "square" as const,
    position: { top: "1/5", right: "1/3" },
    animationDelay: 600,
    opacity: 0.09,
    borderWidth: 2 as const,
  },
  {
    size: "md" as const,
    shape: "triangle" as const,
    position: { top: "2/5", left: "1/12" },
    animationDelay: 1000,
    opacity: 0.1,
    borderWidth: 3 as const,
  },
  {
    size: "lg" as const,
    shape: "square" as const,
    position: { top: "1/2", left: "1/5" },
    animationDelay: 200,
    opacity: 0.06,
    borderWidth: 2 as const,
  },
  {
    size: "sm" as const,
    shape: "diamond" as const,
    position: { top: "2/5", right: "1/12" },
    animationDelay: 1400,
    opacity: 0.11,
    borderWidth: 4 as const,
  },
  {
    size: "md" as const,
    shape: "circle" as const,
    position: { top: "3/5", right: "1/5" },
    animationDelay: 700,
    opacity: 0.07,
    borderWidth: 2 as const,
  },
  {
    size: "lg" as const,
    shape: "diamond" as const,
    position: { bottom: "1/4", left: "1/8" },
    animationDelay: 1800,
    opacity: 0.05,
    borderWidth: 2 as const,
  },
  {
    size: "sm" as const,
    shape: "circle" as const,
    position: { bottom: "1/8", left: "1/3" },
    animationDelay: 300,
    opacity: 0.08,
    borderWidth: 3 as const,
  },
  {
    size: "md" as const,
    shape: "triangle" as const,
    position: { bottom: "1/3", left: "1/6" },
    animationDelay: 1100,
    opacity: 0.07,
    borderWidth: 3 as const,
  },
  {
    size: "xl" as const,
    shape: "square" as const,
    position: { bottom: "1/6", right: "1/8" },
    animationDelay: 500,
    opacity: 0.04,
    borderWidth: 1 as const,
  },
  {
    size: "sm" as const,
    shape: "square" as const,
    position: { bottom: "1/12", right: "1/3" },
    animationDelay: 1500,
    opacity: 0.09,
    borderWidth: 4 as const,
  },
  {
    size: "md" as const,
    shape: "circle" as const,
    position: { bottom: "2/5", right: "1/6" },
    animationDelay: 900,
    opacity: 0.06,
    borderWidth: 2 as const,
  },
  {
    size: "sm" as const,
    shape: "diamond" as const,
    position: { top: "4/5", left: "4/5" },
    animationDelay: 1700,
    opacity: 0.08,
    borderWidth: 2 as const,
  },
  {
    size: "lg" as const,
    shape: "triangle" as const,
    position: { top: "1/10", left: "1/30" },
    animationDelay: 100,
    opacity: 0.04,
    borderWidth: 1 as const,
  },
  {
    size: "md" as const,
    shape: "triangle" as const,
    position: { bottom: "4/5", right: "4/5" },
    animationDelay: 1300,
    opacity: 0.06,
    borderWidth: 2 as const,
  },
  {
    size: "sm" as const,
    shape: "circle" as const,
    position: { bottom: "1/10", left: "4/5" },
    animationDelay: 1900,
    opacity: 0.07,
    borderWidth: 2 as const,
  },
];
